version: "3.9"

services:
  postgres:
    image: postgres:11.5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: De0h52bpNrT6jqy9Z87U
      POSTGRES_USER: datadog
      POSTGRES_DB: test
    networks:
      - backend
    volumes:
      - dbdata:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 0
        delay: 0s
      restart_policy:
        condition: any